Code Cleanup
AlpsBTE/Plot-System pull request #113
Opened 2023-02-27 10:11 UTC by Cinnazeyy

Fix issue: https://github.com/AlpsBTE/Plot-System/issues/112

2023-03-18 22:45 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/commands/CMD_Tpll.java
> +        String[] splitCoords = args[0].split(",");
args can be null

2023-03-18 23:12 UTC, LordTuxn requested changes
I tested the plugin a bit and some menus/commands no longer work properly. All changes need to be tested on the server before merging.

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/commands/admin/CMD_DeletePlot.java
>              sender.sendMessage(Utils.getErrorMessageFormat("You don't have permission to use this command!"));
translation is missing

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/commands/admin/CMD_SetHologram.java
> +            sender.sendMessage(Utils.getErrorMessageFormat("You don't have permission to use this command!"));
translation is missing

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/commands/CMD_Tpll.java
> +        String[] splitCoords = args[0].split(",");
args can be null

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/commands/review/CMD_Review.java
needs to be tested

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/core/menus/ReviewMenu.java
needs to be tested

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/core/menus/PlotMemberMenu.java
needs to be tested

2023-03-18 23:12 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/core/menus/ReviewPlotMenu.java
needs to be tested

2023-03-19 00:27 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/commands/admin/CMD_DeletePlot.java
>              sender.sendMessage(Utils.getErrorMessageFormat("You don't have permission to use this command!"));
There wasn't any translation to begin with and i only fixed formatting! Also, to my knowledge this command has been on the "maybe-to-be-deleted-list" anyways, so i'm not sure if changing it is really necessary.

2023-03-19 00:29 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/commands/admin/CMD_SetHologram.java
> +            sender.sendMessage(Utils.getErrorMessageFormat("You don't have permission to use this command!"));
same here, the goal of this PR is only to cleanup the whole code structure, not to change any logic

2023-03-19 00:35 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/commands/CMD_Tpll.java
> +        String[] splitCoords = args[0].split(",");
fixed in latest commit!

2023-09-03 17:55 UTC, merged