Add a feature to enable shortlinks
AlpsBTE/Plot-System pull request #77
Opened 2022-02-04 11:21 UTC by Nachwahl

This PR adds a feature which enables the plugin to send shortlinks together with the clickable links. This is useful for bedrock players because the bedrock edition doesn't support clickable chat components. For the shortlink backend [Shlink](https://shlink.io/) is being used. 

![](https://media.nachwahl.dev/YFnSug.png)

2022-02-04 13:10 UTC, Cinnazeyy submitted a review, later dismissed
Good job! But its not quite ready...
Refer to my comments for whats to be adressed before merging.

2022-02-04 13:10 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/core/system/plot/PlotHandler.java
> +            if(PlotSystem.getPlugin().getConfigManager().getConfig().getBoolean("shortlink.enable")) {
Please use the ConfigPaths class for all config data rather than passing the config string directly!
Makes it a lot more maintainable.

2022-02-04 13:10 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/utils/Shortlink.java
> +        con.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
Do you really need user-agent here?

2022-02-04 13:10 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/utils/Shortlink.java
> +        URL url = new URL("https://buildthe.earth/rest/v2/short-urls/shorten?apiKey=" + apikey + "&format=txt&longUrl=" + fullURL);
Unless this domain and api is run entirely by main bte, I would remove such a default option as it goes directly against our open and neutral goal for this project!

2022-02-04 13:10 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/utils/Shortlink.java
> +    public static void main(String[] args) {
Please remove this as well!

2022-02-04 13:10 UTC, Cinnazeyy commented on src/main/resources/defaultConfig.yml
> +  host: https://buildthe.earth
Same as Shortlink.java 38

2022-02-04 13:10 UTC, Cinnazeyy commented on src/main/java/com/alpsbte/plotsystem/core/system/plot/PlotHandler.java
> +        } catch (SQLException | IOException ex) {
Might wanna change the logger output too ^^

2022-02-04 13:16 UTC, Georg-code commented on src/main/java/com/alpsbte/plotsystem/utils/Shortlink.java
> +        con.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
Windows user-agent 🤮

2022-02-04 20:59 UTC, Nachwahl commented on src/main/java/com/alpsbte/plotsystem/utils/Shortlink.java
> +        con.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
> Do you really need user-agent here?

Yes, since many ddos mitigation tools (aka. Cloudflare) block incoming requests without a valid User Agent.

2022-02-04 21:06 UTC, Nachwahl commented
@Cinnazeyy All your suggested improvements should be implemented!

2022-02-06 11:53 UTC, LordTuxn requested changes

2022-02-06 11:53 UTC, LordTuxn commented on src/main/resources/defaultConfig.yml
>  config-version: 1.3
Config version needs to be updated to **1.4**
Please also update it here https://github.com/AlpsBTE/Plot-System/blob/f9779bf8b44a341fc6d8a811b074945da89bb42b/src/main/java/com/alpsbte/plotsystem/core/config/ConfigManager.java#L47

2022-02-06 11:53 UTC, LordTuxn commented on src/main/java/com/alpsbte/plotsystem/core/config/ConfigPaths.java
> +    public static final String SHORTLINK = "shortlink.";
Should be private

2022-02-09 21:19 UTC, LordTuxn approved these changes
LGTM

2022-02-09 21:21 UTC, merged